nodeLinker: hoisted

allowBuilds:
  dtrace-provider: true
  esbuild: true
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@expo/eas-build-job@21.1.0'
  - '@expo/eas-json@21.1.0'
  - '@expo/steps@21.1.0'
  - eas-cli@21.1.0
